name: "DiT-XL"

depth: 28
hidden_size: 1152
patch_size: 1     # TODO: patch size can change based
num_heads: 16

attn_type: "jax"
grad_checkpoint: True
dit_block_kwargs:
  grad_checkpoint_attn: True
  grad_checkpoint_mlp: True
  grad_checkpoint_adamlp: True
