name: "DiT-L"

depth: 24
hidden_size: 1024
patch_size: 1     # TODO: patch size can change based
num_heads: 16

attn_type: "jax"
# For memory efficiency
grad_checkpoint: False 
scan_remat: False 
scan_remat_block_size: 4
dit_block_kwargs:
  grad_checkpoint_attn: False 
  grad_checkpoint_mlp: False 
  grad_checkpoint_adamlp: False 
  blockwise_mlp: False 
  blockwise_mlp_chunk_size: 1 
  # Mixed precision
  mlp_dtype: "bfloat16"
  adaln_mlp_dtype: "bfloat16"