name: "DiT-2B"
depth: 24
hidden_size: 2048 
num_heads: 16

patch_size: 1     
attn_type: "jax"
grad_checkpoint: False
dit_block_kwargs:
  grad_checkpoint_attn: False 
  grad_checkpoint_mlp: False 
  grad_checkpoint_adamlp: False 
