defaults:
  - dit_tiny

name: "DiT-Ti-SSM"
attn_type: "ssm"
attn_kwargs:
  d_expansion: 1
  d_state: 256
# attn_kwargs:
#   qk_norm: False             # default is False, but divided by self.scale
#   elu: False 
#   normalizer: constant
#   scale_q: False