depth: 12
hidden_size: 384
num_heads: 6

patch_size: 2
name: "TTT-S-v5"
attn_type: "ttt_lm_bd_v2"
# For memory efficiency
grad_checkpoint: False 
scan_blocks: True 
scan_remat: False 
scan_remat_block_size: 4
dit_block_kwargs:
  grad_checkpoint_attn: True 
  grad_checkpoint_mlp: False 
  grad_checkpoint_adamlp: False 
  blockwise_mlp: False 
  blockwise_mlp_chunk_size: 128
  # Mixed precision
  mlp_dtype: "bfloat16"
  adaln_mlp_dtype: "bfloat16"

attn_kwargs:
  grad_checkpoint_qkv: False 
  grad_checkpoint_out: False 
  qkv_dtype: "bfloat16"
  out_dtype: "bfloat16"
  separate_qkv: False
  proj_norm: True
  mult_norm: False
  apply_gate: False
  sigmoid_learnable_token_idx: True
  mttt_type: "mlp_base"
  use_ar_mask: False
  learn_token_idx: False
  mttt_kwargs:
    hidden_size: null
    num_attention_heads: null
    # https://github.com/test-time-training/ttt-lm-jax/blob/ac8cdc8a43b811afe23c27d7e82eed34a747b19c/ttt/models/model.py#L76 
    conv_width: 4
    # https://github.com/test-time-training/ttt-lm-jax/blob/ac8cdc8a43b811afe23c27d7e82eed34a747b19c/ttt/models/model.py#L64C9-L64C35 
    initializer_range: 0.02
    # https://github.com/test-time-training/ttt-lm-jax/blob/ac8cdc8a43b811afe23c27d7e82eed34a747b19c/ttt/models/model.py#L72C9-L72C31
    mini_batch_size: 16
    # https://github.com/test-time-training/ttt-lm-jax/blob/ac8cdc8a43b811afe23c27d7e82eed34a747b19c/ttt/models/model.py#L63
    max_sequence_length: 16384
    # https://github.com/test-time-training/ttt-lm-jax/blob/ac8cdc8a43b811afe23c27d7e82eed34a747b19c/ttt/models/model.py#L74C9-L74C31
    rope_theta: 10000.0
    # https://github.com/test-time-training/ttt-lm-jax/blob/ac8cdc8a43b811afe23c27d7e82eed34a747b19c/scripts/ttt_mlp/125m.sh#L24C107-L24C129
    ttt_base_lr: 0.1
    ttt_base_lr_init: 0.01
    ttt_base_lr_warmup: 480
    # https://github.com/test-time-training/ttt-lm-jax/blob/ac8cdc8a43b811afe23c27d7e82eed34a747b19c/ttt/models/model.py#L73C1-L74C1
    remat_mini_batch_group_size: 32
    # https://github.com/test-time-training/ttt-lm-jax/blob/ac8cdc8a43b811afe23c27d7e82eed34a747b19c/ttt/models/model.py#L213
    remat_conv: ""
    output_ttt_stats: True
